# Generated by Django 5.2.17 on 2026-09-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('DOCUMENT', 'Documento'), ('PAST_INCIDENT', 'Ocorrência anterior'), ('TECHNICIAN', 'Técnico')], max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_evidence', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='maintenance.investigation')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_evidence', to='assets.document')),
                ('source_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_evidence', to='maintenance.incident')),
                ('source_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provided_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('TECHNICIAN', 'Técnico'), ('SYSTEM', 'Sistema')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_facts', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='maintenance.investigation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('WEAKENED', 'Enfraquecida'), ('DISCARDED', 'Descartada'), ('CONFIRMED_BY_TECHNICIAN', 'Confirmada pelo técnico')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hypotheses', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hypotheses', to='maintenance.investigation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HypothesisEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('SUPPORTS', 'Sustenta'), ('CONTRADICTS', 'Contradiz')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypothesis_links', to='knowledge.evidence')),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='knowledge.hypothesis')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='hypotheses', through='knowledge.HypothesisEvidence', to='knowledge.evidence'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_document__isnull', False), ('source_incident__isnull', True), ('source_technician__isnull', True), ('source_type', 'DOCUMENT')), models.Q(('source_document__isnull', True), ('source_incident__isnull', False), ('source_technician__isnull', True), ('source_type', 'PAST_INCIDENT')), models.Q(('source_document__isnull', True), ('source_incident__isnull', True), ('source_technician__isnull', False), ('source_type', 'TECHNICIAN')), _connector='OR'), name='evidence_has_coherent_provenance'),
        ),
        migrations.AddConstraint(
            model_name='hypothesisevidence',
            constraint=models.UniqueConstraint(fields=('hypothesis', 'evidence', 'relation'), name='unique_evidence_relation_per_hypothesis'),
        ),
    ]
