# Generated by Django 5.2.17 on 2026-09-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MISTRAL', 'Mistral'), ('OPENAI', 'OpenAI'), ('GEMINI', 'Google Gemini'), ('ANTHROPIC', 'Anthropic Claude')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('api_key_encrypted', models.TextField()),
                ('api_key_last_four', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configuration', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization_id'],
            },
        ),
    ]
