# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconfiguration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("MISTRAL", "Mistral"),
                    ("OPENAI", "OpenAI"),
                    ("GEMINI", "Google Gemini"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GROQ", "Groq"),
                ],
                max_length=20,
            ),
        ),
    ]
